AWSTemplateFormatVersion: "2010-09-09"
Description: Sales

Parameters:
  ProjectUniqueIdentifier:
    Default: ""
    Type: String
    Description: "Project Unique Identifier"
  WAFWebAclArn:
    Type: String
    Default: ""
  CDNWebDNSAliases:
    Type: CommaDelimitedList
    Default: "salesportal.com"
  CFWebAppUseDefaultHostname:
    Default: "true"
    AllowedValues:
      - "false"
      - "true"
    Type: String
  CFWebAppACMCertificateArn:
    Type: String
  TagSaledportalRegion:
    AllowedValues:
      - "NAM"
      - "APAC"
      - "EMEA"
      - "US"
      - "LATAM"
    Type: String
    Description: "Tag - SalesPortal Region"
  TagStack:
    Default: "SALES-CDN"
    Type: String
    Description: "Tag - Stack"
  TagEnvironment:
    AllowedValues:
      - "CAT"
      - "DEV"
      - "POC"
      - "PRE-PROD"
      - "PROD"
      - "QA"
      - "QA1"
      - "QA2"
      - "SIT"
      - "STAGE"
      - "TRAINING"
      - "UAT"
    Type: String
    Description: Environment
  TagCostCenter:
    Default: ""
    Type: String
    Description: Tag - Cost Center
  TagCustomer:
    Default: "Sales"
    Type: String
    Description: Tag - Customer
  DeploymentS3BucketName:
    Description: "Deployment S3 Bucket Name"
    Type: String
    Default: "cf-templates-3ja2n3iiafo-us-east-1"
  BucketName:
    Description: "Deployment S3 Bucket Name"
    Type: String
    Default: "test-sales-43543-dev"


Mappings:
  NamingEnvironment:
    "PROD":
      "Code": "prod"
    "PRE-PROD":
      "Code": "preprod"
    "UAT":
      "Code": "uat"
    "QA":
      "Code": "qa"
    "QA1":
      "Code": "qa1"
    "QA2":
      "Code": "qa2"
    "TEST":
      "Code": "test"
    "DEV":
      "Code": "dev"
    "SIT":
      "Code": "sit"
    "CAT":
      "Code": "cat"
    "DR":
      "Code": "dr"

Conditions:
  AlwaysFalse:
    Fn::Equals:
      - "true"
      - "false"
  CFWebAppUseDefaultHostnameCondition:
    Fn::Equals:
      - Ref: CFWebAppUseDefaultHostname
      - "true"

Resources:
  ###### Application S3 Bucket ######
  S3BucketCDN:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: BucketName
      AccessControl: BucketOwnerFullControl
      AccelerateConfiguration:
        AccelerationStatus: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"


  ###### Cloudfront ######
  S3CFOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment:
          !Join [
            "-",
            [
              "sales",
              !Ref ProjectUniqueIdentifier,
              !FindInMap [NamingEnvironment, !Ref TagEnvironment, "Code"],
            ],
          ]

  # CDN CloudFront Creation #
  CDNPortal:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        WebACLId: !Ref WAFWebAclArn #!GetAtt WAF.Outputs.WebACLArn
        HttpVersion: http2
        Aliases:
          Fn::If:
            - CFWebAppUseDefaultHostnameCondition
            - Ref: AWS::NoValue
            - Ref: CDNWebDNSAliases
        ViewerCertificate:
          Fn::If:
            - CFWebAppUseDefaultHostnameCondition
            - CloudFrontDefaultCertificate: true
            - AcmCertificateArn:
                Ref: CFWebAppACMCertificateArn
              MinimumProtocolVersion: TLSv1.2_2019
              SslSupportMethod: sni-only
        Origins:
          - Id: CDNS3Bucket
            DomainName:
              Fn::Join:
                - ""
                - - !Ref BucketName
                  - ".s3.amazonaws.com"
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Join:
                  - ""
                  - - origin-access-identity/cloudfront/
                    - Ref: S3CFOriginAccessIdentity
        Enabled: "true"
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          TargetOriginId: CDNS3Bucket
          CachePolicyId:
            Ref: CFCDNCachePolicy
          OriginRequestPolicyId:
            Ref: CFCDNOriginRequestPolicy
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCachingMinTTL: 300
            ErrorCode: 400
            ResponseCode: 200
            ResponsePagePath: "/"
          - ErrorCachingMinTTL: 300
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: "/"
          - ErrorCachingMinTTL: 300
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: "/"
      Tags:
        - Key: Application
          Value: "cdn"
        - Key: Stack
          Value:
            Ref: TagStack
        - Key: Customer
          Value:
            Ref: TagCustomer
        - Key: Environment
          Value:
            Ref: TagEnvironment
        - Key: Cost Center
          Value:
            Ref: TagCostCenter
        - Key: Name
          Value:
            !Join [
              "-",
              [
                "cf",
                "sales",
                !Ref ProjectUniqueIdentifier,
                !FindInMap [NamingEnvironment, !Ref TagEnvironment, "Code"],
              ],
            ]
        - Key: Description
          Value:
            !Join [
              "-",
              [
                "sales",
                !Ref ProjectUniqueIdentifier,
                !FindInMap [NamingEnvironment, !Ref TagEnvironment, "Code"],
                "Web App Distribution",
              ],
            ]

  CFCDNOriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name:
          !Join [
            "-",
            [
              "cf",
              "sales",
              !Ref ProjectUniqueIdentifier,
              !FindInMap [NamingEnvironment, !Ref TagEnvironment, "Code"],
            ],
          ]
        Comment:
          !Join [
            "-",
            [
              "sales",
              !Ref ProjectUniqueIdentifier,
              !FindInMap [NamingEnvironment, !Ref TagEnvironment, "Code"],
              "CDN Origin Request Policy",
            ],
          ]
        CookiesConfig:
          CookieBehavior: all
        HeadersConfig:
          HeaderBehavior: none
        QueryStringsConfig:
          QueryStringBehavior: all

  CFCDNCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name:
          !Join [
            "-",
            [
              "cf",
              "sales",
              !Ref ProjectUniqueIdentifier,
              !FindInMap [NamingEnvironment, !Ref TagEnvironment, "Code"],
            ],
          ]
        Comment:
          !Join [
            "-",
            [
              "sales",
              !Ref ProjectUniqueIdentifier,
              !FindInMap [NamingEnvironment, !Ref TagEnvironment, "Code"],
              "CDN Cache Policy",
            ],
          ]
        DefaultTTL: 31536000
        MaxTTL: 31536000
        MinTTL: 31536000
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          CookiesConfig:
            CookieBehavior: all
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: all